### PR TITLE
Do not throw exception but save the error as comment in history to pr…

### PR DESCRIPTION
**Pull request by sylvainraye**
…event useless issues in magento processes as the exception block all other processes at this stage

### CODE REVIEW

**Comment by schurter-wallee** [comment]
Hi @sylvainraye 
This exception is thrown intentionally to prevent the credit memo from being created as the refund can still fail in wallee. There is no way to remove the credit memo in that case. The credit memo will be created as soon as the refund is successful in wallee.

**Comment by sylvainraye** [comment]
Well, I see your reason but in the case of my PR, the refund is in pending on wallee and your exception blocks any processes even the creation of the credit memo. And there is no other process or logic in your module which creates the credit memo in a later time. Nothing work. You should retest this use case.

**Comment by schurter-wallee** [comment]
The exception is supposed to block the creation of the credit memo and stop further processes from being triggered, as we cannot tell for sure that the refund will be executed successfully. If it fails, there should not be a credit memo and the processes linked to it should not be triggered either.
And yes, there is code that creates the credit memo as soon as the refund in wallee switches to successful: `Wallee\Payment\Model\Webhook\Listener\Refund\ SuccessfulCommand`.

**Comment by sylvainraye** [comment]
as you wish, by us it didn't work

**Pull request closed without merging**
